# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EvotecIT.OfficeIMO.Studio
PackageVersion: 0.1.9767
Platform:
- Windows.Desktop
InstallerType: msi
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/EvotecIT/OfficeIMO/releases/download/Studio-v0.1.9767/OfficeIMO-Studio-0.1.9767-win-x64.msi
  InstallerSha256: 094928e41737619b4dd4a7a2a1f692db74351fb46f00ead82f064e3250dfca51
  ProductCode: '{BF9CE84B-12E1-4BD5-B60C-90C57716BDB2}'
  AppsAndFeaturesEntries:
  - DisplayName: OfficeIMO Studio
    Publisher: Evotec
    DisplayVersion: 0.1.9767
    ProductCode: '{BF9CE84B-12E1-4BD5-B60C-90C57716BDB2}'
    UpgradeCode: '{C54BB967-362B-48C3-937E-CCBCDD1EA390}'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/EvotecIT/OfficeIMO/releases/download/Studio-v0.1.9767/OfficeIMO-Studio-0.1.9767-win-arm64.msi
  InstallerSha256: 1c5cf38d16540255c6e93d4ea555e47ac574a740f92589a126cb32b169f13947
  ProductCode: '{12B4AC52-3218-4711-AC0B-5C8CC2E9A2B3}'
  AppsAndFeaturesEntries:
  - DisplayName: OfficeIMO Studio
    Publisher: Evotec
    DisplayVersion: 0.1.9767
    ProductCode: '{12B4AC52-3218-4711-AC0B-5C8CC2E9A2B3}'
    UpgradeCode: '{C54BB967-362B-48C3-937E-CCBCDD1EA390}'
ManifestType: installer
ManifestVersion: 1.12.0
